version: '3.8'

services:
  s3:
    image: minio:latest
    ports:
    - "9000:9000"
    - "9001:9001"
    networks:
      s3web
    enviroment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
      
networks:
  s3web:
    driver: bridge
